[project]
name = "mfm-web"
version = "0.1.0"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "numpy",
    "opencv-python",
    "matplotlib",
]

[tool.hatch.build.targets.wheel]
    packages = ["app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"