[project]
name = "mfm-web"
version = "0.1.0"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "numpy",
    "opencv-python"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"